name: Release

on:
  push:
    tags:
      - "*"

jobs:
  build-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dependencies
        run: |
          rustup update stable
          rustup default stable
          sudo apt-get install libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libxkbcommon-dev libssl-dev

      - name: Build
        run: |
          cargo build --release
          strip target/release/calcuuube
          tar -czvf target/release/calcuuube_${{ github.ref_name }}_linux_x64.tar.gz -C target/release/ calcuuube

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: ${{ github.ref_name }}
          draft: true
          files: target/release/calcuuube_${{ github.ref_name }}_linux_x64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
